// ============================================
// MALAGASY LEARNING APP — LESSON DATA
// Easy to extend: just add a new object to the LESSONS array
// ============================================

const LESSONS = [
  {
    id: "intro",
    title: "Introduction to Malagasy",
    emoji: "🇲🇬",
    category: "basics",
    description: "Overview of the language, its origins, and what makes it unique.",
    cards: [
      { front: "Austronesian language from Southeast Asia, settled Madagascar ~2,000 years ago.", front_de: "Austronesische Sprache aus Suedostasien, besiedelte Madagaskar vor ~2.000 Jahren.", back: "Malagasy Origin" },
      { front: "Over 14 million speakers across Madagascar and Mayotte.", front_de: "Ueber 14 Millionen Sprecher auf Madagaskar und Mayotte.", back: "Speakers" },
      { front: "18 regional dialects. Standard = Merina (Antananarivo).", front_de: "18 regionale Dialekte. Standard = Merina (Antananarivo).", back: "Dialects" },
      { front: "Latin alphabet. No C, Q, U, W, X. Pronunciation is phonetic.", front_de: "Lateinisches Alphabet. Kein C, Q, U, W, X. Aussprache ist phonetisch.", back: "Alphabet" },
      { front: "VOS — Verb-Object-Subject. e.g. 'Mihinana vary aho' = Eat rice I.", front_de: "VOS — Verb-Object-Subject. e.g. 'Mihinana vary aho' = Eat rice I.", back: "Word Order" },
      { front: "Adjectives imply 'to be'. 'Mangatsiaka izy' = Cold he/she = 'He is cold'.", front_de: "Adjektive implizieren 'sein'. 'Mangatsiaka izy' = Kalt er/sie = 'Er ist kalt'.", back: "No verb 'to be'" },
    ],
    vocab: [
      { malagasy: "Malagasy", english: "The Malagasy language", german: "Die malagasy Sprache" },
      { malagasy: "Madagasikara", english: "Madagascar", german: "Madagaskar" },
      { malagasy: "teny", english: "language / words", german: "Sprache / Woerter" },
    ],
    quiz: [
      { question: "What language family does Malagasy belong to?", question_de: "Welcher Sprachfamilie gehoert Malagasy an?", options: ["Bantu", "Austronesian", "Semitic", "Indo-European"], options_de: ["Bantu", "Austronesian", "Semitic", "Indo-European"], correct: 1 },
      { question: "How many dialects are spoken in Madagascar?", question_de: "Wie viele Dialekte werden auf Madagaskar gesprochen?", options: ["5", "10", "18", "25"], options_de: ["5", "10", "18", "25"], correct: 2 },
      { question: "What is the standard dialect?", question_de: "Was ist der Standarddialekt?", options: ["Sakalava", "Merina", "Betsileo", "Antandroy"], options_de: ["Sakalava", "Merina", "Betsileo", "Antandroy"], correct: 1 },
      { question: "What word order does Malagasy use?", question_de: "Welche Wortstellung verwendet Malagasy?", options: ["SVO", "SOV", "VOS", "OSV"], options_de: ["SVO", "SOV", "VOS", "OSV"], correct: 2 },
    ]
  },
  {
    id: "alphabet",
    title: "The Alphabet & Sounds",
    emoji: "🔤",
    category: "basics",
    description: "Learn the 4 vowel sounds and key consonant clusters.",
    cards: [
      { front: "Sounds like 'a' in Father. Examples: Salama, Manana", front_de: "Klingt wie 'a' in Vater. Beispiele: Salama, Manana", back: "A [a]" },
      { front: "Sounds like 'ay' in made/pay. Examples: Veloma, teny, enina", front_de: "Klingt wie 'ei' in mein/kein. Beispiele: Veloma, teny, enina", back: "E [ei]" },
      { front: "Sounds like 'ee' in keep. Examples: Misy, mipetraka, tsia", front_de: "Klingt wie 'ie' in lieb. Beispiele: Misy, mipetraka, tsia", back: "I / Y [i:]" },
      { front: "Sounds like 'oo' in pool. Examples: Aho, Voky", front_de: "Klingt wie 'u' in gut. Beispiele: Aho, Voky", back: "O [o/u]" },
      { front: "Difficult diphthong. Example: vaovao (new), tratra (chest)", front_de: "Schwieriger Diphthong. Beispiel: vaovao (neu), tratra (Brust)", back: "ao" },
      { front: "Difficult diphthong. Example: soa (good)", front_de: "Schwieriger Diphthong. Beispiel: soa (gut)", back: "oa" },
      { front: "Affricate. Example: tsotra (simple)", front_de: "Affrikate. Beispiel: tsotra (einfach)", back: "ts" },
      { front: "Pronounced together. Example: drafitra (draft)", front_de: "Zusammen ausgesprochen. Beispiel: drafitra (Entwurf)", back: "dr" },
      { front: "Example: Indrindra (especially)", front_de: "Beispiel: Indrindra (besonders)", back: "ndr" },
      { front: "Example: onja (wave)", front_de: "Beispiel: onja (Welle)", back: "nj" },
    ],
    vocab: [
      { malagasy: "Salama", english: "Hello", german: "Hallo" },
      { malagasy: "Manana", english: "to have", german: "haben" },
      { malagasy: "Veloma", english: "Bye!", german: "Tschuess!" },
      { malagasy: "Misy", english: "there is", german: "es gibt" },
      { malagasy: "Aho", english: "I", german: "ich" },
      { malagasy: "Voky", english: "full", german: "satt / voll" },
      { malagasy: "vaovao", english: "new", german: "neu" },
      { malagasy: "soa", english: "good", german: "gut" },
      { malagasy: "vaovao", english: "new (news)", german: "neu (Nachrichten)" },
      { malagasy: "tratra", english: "chest", german: "Brust" },
      { malagasy: "tsotra", english: "simple", german: "einfach" },
      { malagasy: "Indrindra", english: "especially", german: "besonders" },
      { malagasy: "onja", english: "wave", german: "Welle" },
      { malagasy: "drafitra", english: "draft", german: "Entwurf" },
    ],
    quiz: [
      { question: "How many vowel sounds does Malagasy have?", question_de: "How many vowel sounds does Malagasy have?", options: ["3", "4", "5", "6"], options_de: ["3", "4", "5", "6"], correct: 1 },
      { question: "Which English sound is closest to Malagasy 'E'?", question_de: "Which English sound is closest to Malagasy 'E'?", options: ["eh", "ay", "ee", "oh"], options_de: ["eh", "ay", "ee", "oh"], correct: 1 },
      { question: "Which letters do NOT exist in Malagasy?", question_de: "Which letters do NOT exist in Malagasy?", options: ["a, b, c", "c, q, u, w, x", "j, k, l, m", "p, r, s, t"], options_de: ["a, b, c", "c, q, u, w, x", "j, k, l, m", "p, r, s, t"], correct: 1 },
    ]
  },
  {
    id: "greetings",
    title: "Greetings",
    emoji: "👋",
    category: "conversation",
    description: "Essential greetings and polite expressions.",
    cards: [
      { front: "Hello!", front_de: "Hello!", back: "Manahoana?" },
      { front: "Hi!", front_de: "Hi!", back: "Salama!" },
      { front: "What's up?", front_de: "What's up?", back: "Inona no vaovao?" },
      { front: "Nothing special!", front_de: "Nothing special!", back: "Tsy misy!" },
      { front: "How are you?", front_de: "How are you?", back: "Fahasalamana?" },
      { front: "I'm OK. Thanks.", front_de: "I'm OK. Thanks.", back: "Tsara fa misaotra!" },
      { front: "Welcome!", front_de: "Welcome!", back: "Tonga soa!" },
      { front: "Bye!", front_de: "Bye!", back: "Veloma!" },
      { front: "Thanks!", front_de: "Thanks!", back: "Misaotra!" },
      { front: "Please / Sorry!", front_de: "Please / Sorry!", back: "Azafady!" },
      { front: "Please / Sorry! (formal)", front_de: "Please / Sorry! (formal)", back: "Miala tsiny!" },
      { front: "No problem!", front_de: "No problem!", back: "Tsy misy olana!" },
    ],
    vocab: [
      { malagasy: "Manahoana", english: "Hello", german: "Hallo" },
      { malagasy: "Salama", english: "Hi / Health", german: "Hallo / Gesundheit" },
      { malagasy: "vaovao", english: "news / new", german: "Nachrichten / neu" },
      { malagasy: "Fahasalamana", english: "health / How are you?", german: "Gesundheit / Wie geht es dir?" },
      { malagasy: "Tsara", english: "good / OK", german: "gut / OK" },
      { malagasy: "misaotra", english: "thank you", german: "Danke" },
      { malagasy: "Tonga soa", english: "Welcome", german: "Willkommen" },
      { malagasy: "Veloma", english: "Goodbye", german: "Auf Wiedersehen" },
      { malagasy: "Azafady", english: "Please / Sorry / Excuse me", german: "Bitte / Entschuldigung" },
      { malagasy: "Miala tsiny", english: "Please / Sorry (formal)", german: "Bitte / Entschuldigung (formell)" },
      { malagasy: "olana", english: "problem", german: "Problem" },
      { malagasy: "Salama ohatran'ny", english: "Hello to you too", german: "Hallo auch dir" },
      { malagasy: "Manao ahoana", english: "How are you doing?", german: "Wie geht es dir?" },
      { malagasy: "Tsara be", english: "Very well", german: "Sehr gut" },
      { malagasy: "Tsy dia tsara", english: "Not so well", german: "Nicht so gut" },
      { malagasy: "Aza ny manahy", english: "Don't worry", german: "Mach dir keine Sorgen" },
      { malagasy: "Sambatra", english: "Lucky / Blessed", german: "Gluecklich / Gesegnet" },
      { malagasy: "Miarahaba", english: "Greet / Salute", german: "Gruessen" },
      { malagasy: "Faly", english: "Happy / Glad", german: "Gluecklich / Froh" },
      { malagasy: "Tsy misy", english: "There is not / Nothing", german: "Es gibt nicht / Nichts" },
    ],
    quiz: [
      { question: "What does 'Manahoana?' mean?", question_de: "What does 'Manahoana?' mean?", options: ["Goodbye", "Hello", "Thank you", "Please"], options_de: ["Goodbye", "Hello", "Thank you", "Please"], correct: 1 },
      { question: "How do you say 'How are you?'?", question_de: "How do you say 'How are you?'?", options: ["Salama", "Fahasalamana?", "Veloma", "Misaotra"], options_de: ["Salama", "Fahasalamana?", "Veloma", "Misaotra"], correct: 1 },
      { question: "What does 'Azafady' mean?", question_de: "Was bedeutet 'Azafady'?", options: ["Goodbye", "Please / Sorry", "Welcome", "No"], options_de: ["Goodbye", "Please / Sorry", "Welcome", "No"], correct: 1 },
      { question: "What does 'Tsy misy olana!' mean?", question_de: "What does 'Tsy misy olana!' mean?", options: ["You're welcome", "No problem", "Good morning", "Excuse me"], options_de: ["You're welcome", "No problem", "Good morning", "Excuse me"], correct: 1 },
    ]
  },
  {
    id: "introductions",
    title: "Introductions",
    emoji: "🤝",
    category: "conversation",
    description: "Introducing yourself and asking about others.",
    cards: [
      { front: "What is your name?", front_de: "What is your name?", back: "Iza no anaranao?" },
      { front: "My name is ____, and yours?", front_de: "My name is ____, and yours?", back: "____ no anarako, ary ianao?" },
      { front: "Happy to meet you!", front_de: "Happy to meet you!", back: "Faly mahalala anao!" },
      { front: "Where are you from?", front_de: "Where are you from?", back: "Avy aiza ianao?" },
      { front: "I am from USA.", front_de: "I am from USA.", back: "Avy any Etazonia aho." },
      { front: "What is your job? / What do you do?", front_de: "What is your job? / What do you do?", back: "Inona ny asanao?" },
      { front: "I am a trainee.", front_de: "I am a trainee.", back: "Mpiofana aho." },
      { front: "I learn Malagasy.", front_de: "I learn Malagasy.", back: "Mianatra teny Malagasy aho." },
      { front: "Where will you stay?", front_de: "Where will you stay?", back: "Hipetraka aiza ianao?" },
      { front: "See you later!", front_de: "See you later!", back: "Mandrapihaona!" },
    ],
    vocab: [
      { malagasy: "anarana", english: "name", german: "Name" },
      { malagasy: "avy aiza", english: "from where", german: "woher" },
      { malagasy: "Etazonia", english: "USA", german: "USA" },
      { malagasy: "asa", english: "work / job", german: "Arbeit / Beruf" },
      { malagasy: "Mpiofana", english: "trainee", german: "Auszubildender" },
      { malagasy: "mianatra", english: "to learn", german: "lernen" },
      { malagasy: "mipetraka", english: "to live / to sit", german: "leben / sitzen" },
      { malagasy: "Mandrapihaona", english: "See you later", german: "Bis spaeter" },
      { malagasy: "Frantsay", english: "French", german: "Franzoesisch" },
      { malagasy: "Anglisy", english: "English", german: "Englisch" },
      { malagasy: "teny", english: "language / word", german: "Sprache / Wort" },
      { malagasy: "mpianatra", english: "student", german: "Student / Schueler" },
      { malagasy: "mpampianatra", english: "teacher", german: "Lehrer" },
      { malagasy: "dokotera", english: "doctor", german: "Arzt" },
      { malagasy: "mpiasa", english: "worker", german: "Arbeiter" },
      { malagasy: "mpanjara", english: "volunteer", german: "Freiwilliger" },
      { malagasy: "mpitari-dalana", english: "tour guide", german: "Reisefuehrer" },
      { malagasy: "tompon'asa", english: "employer", german: "Arbeitgeber" },
      { malagasy: "mpiasa an-trano", english: "housekeeper", german: "Haushaelterin" },
      { malagasy: "mpiambina", english: "guard", german: "Waechter" },
      { malagasy: "sakaizana", english: "acquaintance", german: "Bekannter" },
    ],
    quiz: [
      { question: "How do you ask someone's name?", question_de: "How do you ask someone's name?", options: ["Avy aiza ianao?", "Iza no anaranao?", "Inona ny asanao?", "Faly mahalala anao!"], options_de: ["Avy aiza ianao?", "Iza no anaranao?", "Inona ny asanao?", "Faly mahalala anao!"], correct: 1 },
      { question: "What does 'Mianatra teny Malagasy aho.' mean?", question_de: "What does 'Mianatra teny Malagasy aho.' mean?", options: ["I speak Malagasy", "I learn Malagasy", "I love Malagasy", "I teach Malagasy"], options_de: ["I speak Malagasy", "I learn Malagasy", "I love Malagasy", "I teach Malagasy"], correct: 1 },
      { question: "How do you say 'See you later!'?", question_de: "How do you say 'See you later!'?", options: ["Veloma", "Mandrapihaona", "Tonga soa", "Salama"], options_de: ["Veloma", "Mandrapihaona", "Tonga soa", "Salama"], correct: 1 },
    ]
  },
  {
    id: "family",
    title: "Family",
    emoji: "👨‍👩‍👧‍👦",
    category: "vocabulary",
    description: "Family members and relationships.",
    cards: [
      { front: "Family", front_de: "Family", back: "Fianakaviana" },
      { front: "Father", front_de: "Father", back: "Dada" },
      { front: "Mother", front_de: "Mother", back: "Neny" },
      { front: "Older siblings", front_de: "Older siblings", back: "Zoky" },
      { front: "Younger siblings", front_de: "Younger siblings", back: "Zandry" },
      { front: "Grandfather", front_de: "Grandfather", back: "Dadabe" },
      { front: "Grandmother", front_de: "Grandmother", back: "Nenibe" },
      { front: "Children", front_de: "Children", back: "Zanaka" },
      { front: "To be married", front_de: "To be married", back: "Manam-bady" },
      { front: "Single child", front_de: "Single child", back: "Zaza tokana" },
      { front: "Twins", front_de: "Twins", back: "Kambana" },
      { front: "Boy/girlfriend", front_de: "Boy/girlfriend", back: "Sipa" },
      { front: "Friend", front_de: "Friend", back: "Namana" },
      { front: "To be separated", front_de: "To be separated", back: "Nisaraka" },
      { front: "To have", front_de: "To have", back: "Manana" },
    ],
    vocab: [
      { malagasy: "Fianakaviana", english: "Family", german: "Familie" },
      { malagasy: "Dada", english: "Father", german: "Vater" },
      { malagasy: "Neny", english: "Mother", german: "Mutter" },
      { malagasy: "Zoky", english: "Older sibling", german: "aelterer Geschwister" },
      { malagasy: "Zandry", english: "Younger sibling", german: "juengerer Geschwister" },
      { malagasy: "Zanaka", english: "Child", german: "Kind" },
      { malagasy: "Namana", english: "Friend", german: "Freund" },
      { malagasy: "Dadabe", english: "Grandfather", german: "Grossvater" },
      { malagasy: "Nenibe", english: "Grandmother", german: "Grossmutter" },
      { malagasy: "Manam-bady", english: "To be married", german: "Verheiratet sein" },
      { malagasy: "Zaza tokana", english: "Single child", german: "Einzelkind" },
      { malagasy: "Kambana", english: "Twins", german: "Zwillinge" },
      { malagasy: "Sipa", english: "Boyfriend / Girlfriend", german: "Freund / Freundin" },
      { malagasy: "Nisaraka", english: "To be separated", german: "Getrennt sein" },
      { malagasy: "Manana", english: "To have", german: "Haben" },
      { malagasy: "Raimandreny", english: "Parents", german: "Eltern" },
      { malagasy: "Anabavy", english: "Sister", german: "Schwester" },
      { malagasy: "Anadahy", english: "Brother", german: "Bruder" },
      { malagasy: "Vavy", english: "Wife", german: "Frau" },
      { malagasy: "Vady", english: "Husband / Spouse", german: "Ehemann / Partner" },
      { malagasy: "Zanaka vavy", english: "Daughter", german: "Tochter" },
      { malagasy: "Zanaka lahy", english: "Son", german: "Sohn" },
      { malagasy: "Menaky", english: "Cousin", german: "Cousin / Cousine" },
      { malagasy: "Rafozanaka", english: "Nephew / Niece", german: "Neffe / Nichte" },
      { malagasy: "Mpianakavy", english: "Household", german: "Haushalt" },
      { malagasy: "Mponina", english: "Resident / Inhabitant", german: "Bewohner" },
      { malagasy: "Tompokambana", english: "Twin sibling", german: "Zwillingsgeschwister" },
      { malagasy: "Zokiolona", english: "Elder / Senior", german: "Aeltester / Senior" },
      { malagasy: "Ankizy", english: "Kid / Young person", german: "Kind / junge Person" },
      { malagasy: "Mitaiza", english: "To raise (children)", german: "Erziehen (Kinder)" },
      { malagasy: "Miteraka", english: "To give birth", german: "Geben Geburten" },
      { malagasy: "Teraka", english: "Born", german: "Geboren" },
      { malagasy: "Taona", english: "Age / Year", german: "Alter / Jahr" },
      { malagasy: "Miantrana", english: "To adopt", german: "Adoptieren" },
    ],
    quiz: [
      { question: "What does 'Zoky' mean?", question_de: "What does 'Zoky' mean?", options: ["Younger sibling", "Older sibling", "Parent", "Child"], options_de: ["Younger sibling", "Older sibling", "Parent", "Child"], correct: 1 },
      { question: "How do you say 'Mother'?", question_de: "How do you say 'Mother'?", options: ["Dada", "Neny", "Nenibe", "Dadabe"], options_de: ["Dada", "Neny", "Nenibe", "Dadabe"], correct: 1 },
      { question: "What does 'Kambana' mean?", question_de: "What does 'Kambana' mean?", options: ["Single child", "Twins", "Married", "Friend"], options_de: ["Single child", "Twins", "Married", "Friend"], correct: 1 },
    ]
  },
  {
    id: "sentences",
    title: "Basic Sentence Structure",
    emoji: "📝",
    category: "grammar",
    description: "Learn VOS word order, pronouns, negation, and conjugation.",
    content: {
      en: [
        { heading: "Word Order (VOS)", body: "Malagasy uses Verb-Object-Subject order, unlike English. Example: Mihinana vary aho = I eat rice (eat rice I). Example: Mangatsiaka izy = He/she is cold (cold he/she). Negation goes at the very beginning with 'tsy': Tsy mihinana vary aho = I don't eat rice." },
        { heading: "Pronouns", body: "Aho = I | Ianao = You | Izy = He/She. Isika = We (incl.) | Izahay = We (excl.). Ianareo = You (pl.) | Izireo = They. Note: No 'to be' verb needed. 'Mangatsiaka izy' literally = Cold he/she." },
        { heading: "Tenses", body: "Present: mi- prefix | Future: hi- prefix | Past: ni- prefix. mihinana = eat (now) | hihinana = will eat | nihinana = ate. These prefixes attach directly to the verb root. No person or number changes." }
      ],
      de: [
        { heading: "Wortstellung (VOS)", body: "Malagasy verwendet Verb-Objekt-Subjekt-Reihenfolge. Beispiel: Mihinana vary aho = Ich esse Reis (esse Reis ich). Beispiel: Mangatsiaka izy = Er/Sie ist kalt (kalt er/sie). Verneinung steht ganz am Anfang mit 'tsy': Tsy mihinana vary aho = Ich esse keinen Reis." },
        { heading: "Pronomen", body: "Aho = Ich | Ianao = Du | Izy = Er/Sie. Isika = Wir (inkl.) | Izahay = Wir (exkl.). Ianareo = Ihr | Izireo = Sie. Hinweis: Kein 'sein'-Verb noetig. 'Mangatsiaka izy' = Kalt er/sie." },
        { heading: "Zeiten", body: "Gegenwart: mi-Praefix | Zukunft: hi-Praefix | Vergangenheit: ni-Praefix. mihinana = essen (jetzt) | hihinana = werde essen | nihinana = aß. Diese Praefixe werden direkt an den Verbstamm angehaengt. Keine Person- oder Zahlaenderungen." }
      ]
    },
    vocab: [
      { malagasy: "Mihinana", english: "to eat (present)", german: "essen (Gegenwart)" },
      { malagasy: "Hihinana", english: "will eat (future)", german: "werde essen (Zukunft)" },
      { malagasy: "Nihinana", english: "ate (past)", german: "aß (Vergangenheit)" },
      { malagasy: "vary", english: "rice", german: "Reis" },
      { malagasy: "Misotro", english: "to drink", german: "trinken" },
      { malagasy: "rano", english: "water", german: "Wasser" },
      { malagasy: "Tia", english: "to like", german: "moegen" },
      { malagasy: "Tsy", english: "no / not", german: "nein / nicht" },
      { malagasy: "Aho", english: "I / I am", german: "Ich / Ich bin" },
      { malagasy: "Ianao", english: "You / You are", german: "Du / Du bist" },
      { malagasy: "Izy", english: "He/She / He is/She is", german: "Er/Sie" },
      { malagasy: "Isika", english: "We (inclusive)", german: "Wir (inklusiv)" },
      { malagasy: "Izahay", english: "We (exclusive)", german: "Wir (exklusiv)" },
      { malagasy: "Ianareo", english: "You (plural)", german: "Ihr" },
      { malagasy: "Izireo", english: "They", german: "Sie" },
      { malagasy: "Misy", english: "there is / exists", german: "es gibt / existiert" },
      { malagasy: "Tsy misy", english: "there is not", german: "es gibt nicht" },
      { malagasy: "Ity", english: "this", german: "dies" },
      { malagasy: "Iry", english: "that", german: "das" },
      { malagasy: "Ireo", english: "these / those", german: "diese / jene" },
      { malagasy: "Dia", english: "then / and (connector)", german: "dann / und (Verbinder)" },
      { malagasy: "Fa", english: "but", german: "aber" },
      { malagasy: "Satria", english: "because", german: "weil" },
      { malagasy: "Raha", english: "if", german: "wenn" },
      { malagasy: "Na", english: "or", german: "oder" },
      { malagasy: "ary", english: "and", german: "und" },
      { malagasy: "izany", english: "that / it", german: "das / es" },
      { malagasy: "koa", english: "too / also", german: "zu / auch" },
      { malagasy: "ve", english: "question particle", german: "Fragepartikel" },
      { malagasy: "angaha", english: "question particle (polite)", german: "Fragepartikel (hoeflich)" },
    ],
    quiz: [
      { question: "What is the word order in Malagasy?", question_de: "What is the word order in Malagasy?", options: ["SVO", "VOS", "SOV", "OVS"], options_de: ["SVO", "VOS", "SOV", "OVS"], correct: 1 },
      { question: "How do you say 'I don't eat rice'?", question_de: "How do you say 'I don't eat rice'?", options: ["Mihinana vary aho", "Tsy mihinana vary aho", "Tsy vary mihinana aho", "Vary tsy mihinana aho"], options_de: ["Mihinana vary aho", "Tsy mihinana vary aho", "Tsy vary mihinana aho", "Vary tsy mihinana aho"], correct: 1 },
      { question: "What does the prefix 'h-' indicate?", question_de: "What does the prefix 'h-' indicate?", options: ["Past", "Present", "Future", "Negative"], options_de: ["Past", "Present", "Future", "Negative"], correct: 2 },
      { question: "What does the prefix 'n-' indicate?", question_de: "What does the prefix 'n-' indicate?", options: ["Past", "Future", "Negative", "Question"], options_de: ["Past", "Future", "Negative", "Question"], correct: 0 },
    ]
  },
  {
    id: "needs",
    title: "Basic Needs",
    emoji: "🍽️",
    category: "conversation",
    description: "Expressing needs, feelings, and asking for things.",
    cards: [
      { front: "I am tired.", front_de: "I am tired.", back: "Reraka aho." },
      { front: "I am hungry.", front_de: "I am hungry.", back: "Noana aho." },
      { front: "I am full.", front_de: "I am full.", back: "Voky aho." },
      { front: "I am thirsty.", front_de: "I am thirsty.", back: "Mangetaheta aho." },
      { front: "Where is the toilet?", front_de: "Where is the toilet?", back: "Aiza ny kabone?" },
      { front: "I want to drink water.", front_de: "I want to drink water.", back: "Te hisotro rano aho." },
      { front: "I want to sleep.", front_de: "I want to sleep.", back: "Te hatory aho." },
      { front: "I want to eat.", front_de: "I want to eat.", back: "Te hisakafo aho." },
      { front: "I want to go out.", front_de: "I want to go out.", back: "Te hivoaka aho." },
      { front: "I am hot.", front_de: "I am hot.", back: "Mafana aho." },
      { front: "I am cold.", front_de: "I am cold.", back: "Mangatsiaka aho." },
      { front: "I need ___ please.", front_de: "I need ___ please.", back: "Mila ___ aho azafady." },
      { front: "Give me ___ please.", front_de: "Give me ___ please.", back: "Omeo ___ aho azafady." },
      { front: "Can I have ___ please?", front_de: "Can I have ___ please?", back: "Afaka mahazo ___ ve aho azafady?" },
    ],
    vocab: [
      { malagasy: "Reraka", english: "tired", german: "muede" },
      { malagasy: "Noana", english: "hungry", german: "hungrig" },
      { malagasy: "Voky", english: "full", german: "satt / voll" },
      { malagasy: "Mangetaheta", english: "thirsty", german: "durstig" },
      { malagasy: "kabone", english: "toilet", german: "Toilette" },
      { malagasy: "Te", english: "want", german: "wollen" },
      { malagasy: "hatory", english: "to sleep", german: "schlafen" },
      { malagasy: "hisakafo", english: "to eat (meal)", german: "essen (Mahlzeit)" },
      { malagasy: "hivoaka", english: "to go out", german: "ausgehen" },
      { malagasy: "Mafana", english: "hot", german: "heiss" },
      { malagasy: "Mangatsiaka", english: "cold", german: "kalt" },
      { malagasy: "Mila", english: "need", german: "brauchen" },
      { malagasy: "Omeo", english: "give", german: "geben" },
      { malagasy: "Afaka", english: "can / able", german: "koennen / faehig" },
      { malagasy: "mahazo", english: "to get / receive", german: "bekommen / erhalten" },
      { malagasy: "Azafady", english: "please / sorry", german: "bitte / entschuldigung" },
      { malagasy: "Ampy", english: "enough", german: "genug" },
      { malagasy: "Ladosy", english: "shower", german: "Dusche" },
      { malagasy: "Po", english: "pee pot", german: "Topf" },
      { malagasy: "Tsy tia hena", english: "I don't like meat", german: "Ich mag kein Fleisch" },
      { malagasy: "Te-matory", english: "sleepy", german: "schlaefrig" },
      { malagasy: "Matavy", english: "fat / overweight", german: "fett / uebergewichtig" },
      { malagasy: "Mahia", english: "thin / slim", german: "duenn / schlank" },
      { malagasy: "Marary", english: "sick", german: "krank" },
      { malagasy: "Fahasalamana", english: "health", german: "Gesundheit" },
      { malagasy: "Clinika", english: "clinic", german: "Klinik" },
      { malagasy: "Hopitaly", english: "hospital", german: "Krankenhaus" },
      { malagasy: "Fanafody", english: "medicine", german: "Medizin" },
      { malagasy: "Dokotera", english: "doctor", german: "Arzt" },
      { malagasy: "Nurse", english: "nurse", german: "Krankenschwester" },
      { malagasy: "Mampahory", english: "to hurt", german: "verletzen" },
      { malagasy: "Mitsabo", english: "to heal / treat", german: "heilen / behandeln" },
      { malagasy: "Vaksiny", english: "vaccine", german: "Impfstoff" },
      { malagasy: "Arety", english: "disease", german: "Krankheit" },
      { malagasy: "Tazo", english: "fever", german: "Fieber" },
      { malagasy: "Mangatsiaka (tarehy)", english: "pale", german: "blass" },
      { malagasy: "Mafana (tarehy)", english: "flushed", german: "geroetet" },
    ],
    quiz: [
      { question: "How do you say 'I am hungry'?", question_de: "How do you say 'I am hungry'?", options: ["Voky aho", "Noana aho", "Reraka aho", "Mafana aho"], options_de: ["Voky aho", "Noana aho", "Reraka aho", "Mafana aho"], correct: 1 },
      { question: "What does 'Te hatory aho.' mean?", question_de: "What does 'Te hatory aho.' mean?", options: ["I want to eat", "I want to sleep", "I want to drink", "I want to go"], options_de: ["I want to eat", "I want to sleep", "I want to drink", "I want to go"], correct: 1 },
      { question: "How do you ask 'Where is the toilet?'?", question_de: "How do you ask 'Where is the toilet?'?", options: ["Aiza ny rano?", "Aiza ny kabone?", "Aiza ny vary?", "Aiza ny mofo?"], options_de: ["Aiza ny rano?", "Aiza ny kabone?", "Aiza ny vary?", "Aiza ny mofo?"], correct: 1 },
    ]
  },
  {
    id: "questions",
    title: "Question Words",
    emoji: "❓",
    category: "grammar",
    description: "Essential question words and example sentences.",
    content: {
      en: [
        { heading: "Content Questions", body: "Who? = Iza? | Where? = Aiza? | What? = Inona? | How many? = Firy? | What time? = Amin'ny firy? | When? = Oviana? | How much? = Hoatrinona? | Why? = Fa maninona? | How? = Ahoana? Questions keep normal VOS word order. The question word goes where the answer would be." },
        { heading: "Yes/No Questions", body: "Add 've' at the end of a statement to make it yes/no. Example: Misy vary ve? = Is there rice? Example: Manao ahoana ve ianao? = How are you? (formal). Polite version uses 'angaha' instead of 've'." },
        { heading: "When in Statements", body: "For 'when' in statements (not questions), use 'rehefa'. Example: Rehefa tonga aho, dia mihinana vary aho. = When I arrive, I eat rice." }
      ],
      de: [
        { heading: "Inhaltsfragen", body: "Wer? = Iza? | Wo? = Aiza? | Was? = Inona? | Wie viele? = Firy? | Wie viel Uhr? = Amin'ny firy? | Wann? = Oviana? | Wie viel? = Hoatrinona? | Warum? = Fa maninona? | Wie? = Ahoana? Fragen behalten die normale VOS-Wortstellung. Das Fragewort steht dort, wo die Antwort waere." },
        { heading: "Ja/Nein-Fragen", body: "Fuege 've' am Ende einer Aussage hinzu fuer Ja/Nein. Beispiel: Misy vary ve? = Gibt es Reis? Beispiel: Manao ahoana ve ianao? = Wie geht es dir? (formell). Die hoefliche Version verwendet 'angaha' statt 've'." },
        { heading: "Wann in Aussagen", body: "Fuer 'wann' in Aussagen (nicht Fragen) verwende 'rehefa'. Beispiel: Rehefa tonga aho, dia mihinana vary aho. = Wenn ich ankomme, esse ich Reis." }
      ]
    },
    vocab: [
      { malagasy: "Ve", english: "Question marker (yes/no)", german: "Fragezeichen (Ja/Nein)" },
      { malagasy: "Iza", english: "Who", german: "Wer" },
      { malagasy: "Aiza", english: "Where", german: "Wo" },
      { malagasy: "Inona", english: "What", german: "Was" },
      { malagasy: "Firy", english: "How many", german: "Wie viele" },
      { malagasy: "Oviana", english: "When (question)", german: "Wann (Frage)" },
      { malagasy: "Rehefa", english: "When (statement)", german: "Wann (Aussage)" },
      { malagasy: "Ahoana", english: "How", german: "Wie" },
      { malagasy: "Fa maninona", english: "Why", german: "Warum" },
      { malagasy: "Amin'ny firy", english: "What time", german: "Wie viel Uhr" },
      { malagasy: "Hoatrinona", english: "How much", german: "Wie viel" },
      { malagasy: "Aiza ny ...", english: "Where is the ...", german: "Wo ist der/die/das ..." },
      { malagasy: "Inona no ...", english: "What is the ...", german: "Was ist der/die/das ..." },
      { malagasy: "Iza no ...", english: "Who is the ...", german: "Wer ist der/die/das ..." },
      { malagasy: "Firy ny ...", english: "How many ...", german: "Wie viele ..." },
      { malagasy: "Nahoana?", english: "How come?", german: "Wieso?" },
      { malagasy: "Inona no antony?", english: "What is the reason?", german: "Was ist der Grund?" },
      { malagasy: "Aiza no mety?", english: "Where is it suitable?", german: "Wo ist es passend?" },
      { malagasy: "Ahoana no anaranao?", english: "What is your name? (alt)", german: "Wie ist dein Name? (alt)" },
      { malagasy: "Inona no tianao?", english: "What do you want?", german: "Was willst du?" },
      { malagasy: "Aiza no mipetraka ianao?", english: "Where do you live?", german: "Wo wohnst du?" },
      { malagasy: "Oviana no hianaranao?", english: "When will you study?", german: "Wann wirst du lernen?" },
      { malagasy: "Ahoana ny toetranao?", english: "How is your health?", german: "Wie ist deine Gesundheit?" },
      { malagasy: "Hoatrinona ny vidiny?", english: "What is the price?", german: "Was ist der Preis?" },
      { malagasy: "Firy ny taonanao?", english: "How old are you?", german: "Wie alt bist du?" },
    ],
    quiz: [
      { question: "What does 'Aiza?' mean?", question_de: "What does 'Aiza?' mean?", options: ["Who", "Where", "What", "When"], options_de: ["Who", "Where", "What", "When"], correct: 1 },
      { question: "Which word is used for 'when' in statements (not questions)?", question_de: "Which word is used for 'when' in statements (not questions)?", options: ["Oviana", "Rehefa", "Ahoana", "Aiza"], options_de: ["Oviana", "Rehefa", "Ahoana", "Aiza"], correct: 1 },
      { question: "How do you ask 'How much'?", question_de: "How do you ask 'How much'?", options: ["Firy", "Hoatrinona", "Inona", "Ahoana"], options_de: ["Firy", "Hoatrinona", "Inona", "Ahoana"], correct: 1 },
    ]
  },
  {
    id: "commands",
    title: "Commands & Requests",
    emoji: "🙏",
    category: "conversation",
    description: "Common commands, requests, and polite expressions.",
    cards: [
      { front: "Yes", front_de: "Yes", back: "Eny" },
      { front: "No", front_de: "No", back: "Tsia" },
      { front: "Come here!", front_de: "Come here!", back: "Avia aty!" },
      { front: "Wait!", front_de: "Wait!", back: "Andraso!" },
      { front: "Let's go / Come on!", front_de: "Let's go / Come on!", back: "Ndao handeha!" },
      { front: "False / Untrue", front_de: "False / Untrue", back: "Diso" },
      { front: "True", front_de: "True", back: "Marina" },
      { front: "That is enough!", front_de: "That is enough!", back: "Ampy izay!" },
      { front: "Understand?", front_de: "Understand?", back: "Azo?" },
      { front: "I need (coke) please.", front_de: "I need (coke) please.", back: "Mila (koka) aho azafady." },
      { front: "Give me (water) please.", front_de: "Give me (water) please.", back: "Omeo (rano) aho azafady." },
      { front: "Can I have (a glass) please?", front_de: "Can I have (a glass) please?", back: "Afaka mahazo (vera) ve aho azafady?" },
    ],
    vocab: [
      { malagasy: "Eny", english: "Yes", german: "Ja" },
      { malagasy: "Tsia", english: "No", german: "Nein" },
      { malagasy: "Avia aty", english: "Come here", german: "Komm her" },
      { malagasy: "Andraso", english: "Wait", german: "Warte" },
      { malagasy: "Ndao handeha", english: "Let's go", german: "Los geht's" },
      { malagasy: "Diso", english: "False", german: "Falsch" },
      { malagasy: "Marina", english: "True", german: "Wahr" },
      { malagasy: "Ampy izay", english: "That's enough", german: "Das reicht" },
      { malagasy: "Azonao atao ve?", english: "Can you do it?", german: "Kannst du das machen?" },
      { malagasy: "Aleo", english: "Better / Rather", german: "Besser / Eher" },
      { malagasy: "Tsara", english: "Good / OK", german: "Gut / OK" },
      { malagasy: "Azafady miditra", english: "Please come in", german: "Bitte komm rein" },
      { malagasy: "Miala amin'ny", english: "Get away from", german: "Weg von" },
      { malagasy: "Mijanona", english: "Stop", german: "Stopp" },
      { malagasy: "Miverena", english: "Come back", german: "Komm zurueck" },
      { malagasy: "Mandrosoa", english: "Go ahead", german: "Mach weiter" },
      { malagasy: "Aza manao izany", english: "Don't do that", german: "Mach das nicht" },
      { malagasy: "Manaova azafady", english: "Please do it", german: "Bitte mach es" },
      { malagasy: "Mba omeo aho", english: "Please give me", german: "Bitte gib mir" },
      { malagasy: "Afaka mijery ve?", english: "Can I see?", german: "Kann ich sehen?" },
      { malagasy: "Alefaso", english: "Send it", german: "Schick es" },
      { malagasy: "Tadidio", english: "Remember", german: "Erinnere dich" },
      { malagasy: "Aza hadinoina", english: "Don't forget", german: "Vergiss nicht" },
      { malagasy: "Mianara tsara", english: "Study well", german: "Lerne gut" },
      { malagasy: "Miandrasa kely", english: "Wait a moment", german: "Warte einen Moment" },
      { malagasy: "Mangatahana", english: "To request", german: "Bitten" },
      { malagasy: "Manaiky aho", english: "I agree", german: "Ich stimme zu" },
      { malagasy: "Manao ahoana", english: "How are you?", german: "Wie geht es dir?" },
      { malagasy: "Veloma ianao", english: "Goodbye to you", german: "Auf Wiedersehen" },
    ],
    quiz: [
      { question: "What does 'Avia aty!' mean?", question_de: "What does 'Avia aty!' mean?", options: ["Go away", "Come here", "Wait", "Let's go"], options_de: ["Go away", "Come here", "Wait", "Let's go"], correct: 1 },
      { question: "How do you say 'No'?", question_de: "How do you say 'No'?", options: ["Eny", "Tsia", "Diso", "Marina"], options_de: ["Eny", "Tsia", "Diso", "Marina"], correct: 1 },
      { question: "What does 'Ampy izay!' mean?", question_de: "What does 'Ampy izay!' mean?", options: ["More please", "That's enough", "I understand", "Wait"], options_de: ["More please", "That's enough", "I understand", "Wait"], correct: 1 },
    ]
  },
  {
    id: "numbers",
    title: "Numbers",
    emoji: "🔢",
    category: "vocabulary",
    description: "Counting in Malagasy — read from right to left!",
    cards: [
      { front: "One", front_de: "One", back: "1 - Iray" },
      { front: "Two", front_de: "Two", back: "2 - Roa" },
      { front: "Three", front_de: "Three", back: "3 - Telo" },
      { front: "Four", front_de: "Four", back: "4 - Efatra" },
      { front: "Five", front_de: "Five", back: "5 - Dimy" },
      { front: "Six", front_de: "Six", back: "6 - Enina" },
      { front: "Seven", front_de: "Seven", back: "7 - Fito" },
      { front: "Eight", front_de: "Eight", back: "8 - Valo" },
      { front: "Nine", front_de: "Nine", back: "9 - Sivy" },
      { front: "Ten", front_de: "Ten", back: "10 - Folo" },
      { front: "Forty", front_de: "Forty", back: "40 - Efapolo" },
      { front: "Hundred", front_de: "Hundred", back: "100 - Zato" },
      { front: "Thousand", front_de: "Thousand", back: "1,000 - Arivo" },
      { front: "Ten thousand", front_de: "Ten thousand", back: "10,000 - Iray alina" },
      { front: "Hundred thousand", front_de: "Hundred thousand", back: "100,000 - Iray hetsy" },
      { front: "Use 'amby' to connect up to 199. Use 'sy' after 199.", front_de: "Use 'amby' to connect up to 199. Use 'sy' after 199.", back: "Note: amby vs sy" },
    ],
    vocab: [
      { malagasy: "Iray", english: "One", german: "Eins" },
      { malagasy: "Roa", english: "Two", german: "Zwei" },
      { malagasy: "Telo", english: "Three", german: "Drei" },
      { malagasy: "Dimy", english: "Five", german: "Fuenf" },
      { malagasy: "Folo", english: "Ten", german: "Zehn" },
      { malagasy: "Zato", english: "Hundred", german: "Hundert" },
      { malagasy: "Arivo", english: "Thousand", german: "Tausend" },
      { malagasy: "Iray alina", english: "Ten thousand", german: "Zehntausend" },
      { malagasy: "Iray hetsy", english: "Hundred thousand", german: "Hunderttausend" },
      { malagasy: "Efatra", english: "Four", german: "Vier" },
      { malagasy: "Enina", english: "Six", german: "Sechs" },
      { malagasy: "Fito", english: "Seven", german: "Sieben" },
      { malagasy: "Valo", english: "Eight", german: "Acht" },
      { malagasy: "Sivy", english: "Nine", german: "Neun" },
      { malagasy: "Efapolo", english: "Forty", german: "Vierzig" },
      { malagasy: "Sivifolo", english: "Ninety", german: "Neunzig" },
      { malagasy: "Telonjato", english: "Three hundred", german: "Dreihundert" },
      { malagasy: "Sivinjato", english: "Nine hundred", german: "Neunhundert" },
      { malagasy: "Dimy arivo", english: "Five thousand", german: "Fuenftausend" },
      { malagasy: "Fito arivo", english: "Seven thousand", german: "Siebentausend" },
      { malagasy: "Roa alina", english: "Twenty thousand", german: "Zwanzigtausend" },
      { malagasy: "Enina alina", english: "Sixty thousand", german: "Sechzigtausend" },
      { malagasy: "Efatra hetsy", english: "Four hundred thousand", german: "Vierhunderttausend" },
      { malagasy: "Valo hetsy", english: "Eight hundred thousand", german: "Achthunderttausend" },
      { malagasy: "amby", english: "and (for numbers up to 199)", german: "und (fuer Zahlen bis 199)" },
      { malagasy: "sy", english: "and (for numbers after 199)", german: "und (fuer Zahlen nach 199)" },
      { malagasy: "Maro", english: "many", german: "viele" },
      { malagasy: "Vitsy", english: "few", german: "wenige" },
      { malagasy: " rehetra", english: "all / every", german: "alle / jede" },
      { malagasy: "Sasany", english: "some", german: "einige" },
      { malagasy: "Tsiafa", english: "none / zero", german: "keine / Null" },
      { malagasy: "Voalohany", english: "First", german: "Erste" },
      { malagasy: "Faharoa", english: "Second", german: "Zweite" },
      { malagasy: "Fahatelo", english: "Third", german: "Dritte" },
      { malagasy: "Farany", english: "Last", german: "Letzte" },
      { malagasy: "Amin'ny", english: "At (time/number)", german: "Um (Zeit/Zahl)" },
      { malagasy: "Firy", english: "How many", german: "Wie viele" },
      { malagasy: "Hoatrinona", english: "How much (price)", german: "Wie viel (Preis)" },
    ],
    quiz: [
      { question: "What does 'Enina' mean?", question_de: "What does 'Enina' mean?", options: ["5", "6", "7", "8"], options_de: ["5", "6", "7", "8"], correct: 1 },
      { question: "How do you say 100?", question_de: "How do you say 100?", options: ["Folo", "Zato", "Arivo", "Alina"], options_de: ["Folo", "Zato", "Arivo", "Alina"], correct: 1 },
      { question: "What does 'Arivo' mean?", question_de: "What does 'Arivo' mean?", options: ["100", "1,000", "10,000", "100,000"], options_de: ["100", "1,000", "10,000", "100,000"], correct: 1 },
    ]
  },
  {
    id: "food",
    title: "Food & Drinks",
    emoji: "🍛",
    category: "vocabulary",
    description: "Essential food vocabulary for daily meals.",
    cards: [
      { front: "Food", front_de: "Food", back: "Sakafo" },
      { front: "Rice", front_de: "Rice", back: "Vary" },
      { front: "Side-dishes", front_de: "Side-dishes", back: "Laoka" },
      { front: "Bread", front_de: "Bread", back: "Mofo" },
      { front: "Meat", front_de: "Meat", back: "Hena" },
      { front: "Pork", front_de: "Pork", back: "Henakisoa" },
      { front: "Beef", front_de: "Beef", back: "Henomby" },
      { front: "Chicken", front_de: "Chicken", back: "Akoho" },
      { front: "Fish", front_de: "Fish", back: "Trondro" },
      { front: "Eggs", front_de: "Eggs", back: "Atody" },
      { front: "Vegetable", front_de: "Vegetable", back: "Legioma" },
      { front: "Greens", front_de: "Greens", back: "Anana" },
      { front: "Potatoes", front_de: "Potatoes", back: "Ovy" },
      { front: "Tomato", front_de: "Tomato", back: "Voatabia" },
      { front: "Fruit", front_de: "Fruit", back: "Voankazo" },
      { front: "Papaya", front_de: "Papaya", back: "Papay" },
      { front: "Mango", front_de: "Mango", back: "Manga" },
      { front: "Orange", front_de: "Orange", back: "Voasary" },
      { front: "Water", front_de: "Water", back: "Rano" },
      { front: "Coffee", front_de: "Coffee", back: "Kafe" },
      { front: "Tea", front_de: "Tea", back: "Dite" },
      { front: "Milk", front_de: "Milk", back: "Ronono" },
    ],
    vocab: [
      { malagasy: "Vary", english: "Rice", german: "Reis" },
      { malagasy: "Laoka", english: "Side-dish", german: "Beilage" },
      { malagasy: "Hena", english: "Meat", german: "Fleisch" },
      { malagasy: "Henakisoa", english: "Pork", german: "Schweinefleisch" },
      { malagasy: "Henomby", english: "Beef", german: "Rindfleisch" },
      { malagasy: "Akoho", english: "Chicken", german: "Huhn" },
      { malagasy: "Trondro", english: "Fish", german: "Fisch" },
      { malagasy: "Atody", english: "Eggs", german: "Eier" },
      { malagasy: "Voatabia", english: "Tomato", german: "Tomate" },
      { malagasy: "Kafe", english: "Coffee", german: "Kaffee" },
      { malagasy: "Sakafo", english: "Food", german: "Essen" },
      { malagasy: "Mofo", english: "Bread", german: "Brot" },
      { malagasy: "Legioma", english: "Vegetable", german: "Gemuese" },
      { malagasy: "Anana", english: "Greens", german: "Gruenzeug" },
      { malagasy: "Ovy", english: "Potatoes", german: "Kartoffeln" },
      { malagasy: "Voankazo", english: "Fruit", german: "Obst" },
      { malagasy: "Papay", english: "Papaya", german: "Papaya" },
      { malagasy: "Manga", english: "Mango", german: "Mango" },
      { malagasy: "Voasary", english: "Orange", german: "Orange" },
      { malagasy: "Rano", english: "Water", german: "Wasser" },
      { malagasy: "Dite", english: "Tea", german: "Tee" },
      { malagasy: "Ronono", english: "Milk", german: "Milch" },
      { malagasy: "Menaka", english: "Oil", german: "Oel" },
      { malagasy: "Sira", english: "Salt", german: "Salz" },
      { malagasy: "Sakay", english: "Chili", german: "Chili" },
      { malagasy: "Siramamy", english: "Sugar", german: "Zucker" },
      { malagasy: "Poavra", english: "Pepper", german: "Pfeffer" },
      { malagasy: "Karoty", english: "Carrot", german: "Karotte" },
      { malagasy: "voanjobory", english: "Round beans", german: "Runde Bohnen" },
      { malagasy: "Tsaramaso", english: "Beans", german: "Bohnen" },
      { malagasy: "Mananasy", english: "Pineapple", german: "Ananas" },
      { malagasy: "Jus", english: "Juice", german: "Saft" },
      { malagasy: "Kôka", english: "Coca-cola", german: "Coca-Cola" },
      { malagasy: "Limonady", english: "Lemonade", german: "Limonade" },
      { malagasy: "Ranon'ampango", english: "Rice-water", german: "Reiswasser" },
      { malagasy: "Haninkotrana", english: "Snack", german: "Snack" },
      { malagasy: "Mangahazo", english: "Cassava", german: "Maniok" },
      { malagasy: "Katsaka", english: "Corn", german: "Mais" },
      { malagasy: "Vomanga", english: "Sweet potato", german: "Suesskartoffel" },
      { malagasy: "Episy", english: "Spices", german: "Gewuerze" },
      { malagasy: "Mihinana", english: "To eat", german: "Essen" },
      { malagasy: "Misotro", english: "To drink", german: "Trinken" },
      { malagasy: "mankafy", english: "To enjoy (food)", german: "Geniessen (Essen)" },
      { malagasy: "manamboatra", english: "To prepare (food)", german: "Zubereiten (Essen)" },
      { malagasy: "mampangatsiaka", english: "To cool", german: "Kuehlen" },
      { malagasy: "mangatsiaka", english: "Cold (drink)", german: "Kalt (Getraenk)" },
      { malagasy: "mafana", english: "Hot (food)", german: "Heiss (Essen)" },
      { malagasy: "Matsiro", english: "Delicious", german: "Lecker" },
      { malagasy: "tsy matsiro", english: "Not delicious", german: "Nicht lecker" },
      { malagasy: "Voky", english: "Full (ate enough)", german: "Satt" },
      { malagasy: "Noana", english: "Hungry", german: "Hungrig" },
      { malagasy: "Mangetaheta", english: "Thirsty", german: "Durstig" },
    ],
    quiz: [
      { question: "What is the staple food in Madagascar?", question_de: "What is the staple food in Madagascar?", options: ["Mofo", "Vary", "Hena", "Voankazo"], options_de: ["Mofo", "Vary", "Hena", "Voankazo"], correct: 1 },
      { question: "What does 'Laoka' mean?", question_de: "What does 'Laoka' mean?", options: ["Rice", "Side-dishes", "Meat", "Fruit"], options_de: ["Rice", "Side-dishes", "Meat", "Fruit"], correct: 1 },
      { question: "What does 'Henakisoa' mean?", question_de: "What does 'Henakisoa' mean?", options: ["Beef", "Pork", "Chicken", "Fish"], options_de: ["Beef", "Pork", "Chicken", "Fish"], correct: 1 },
    ]
  },
  {
    id: "days",
    title: "Days & Time",
    emoji: "📅",
    category: "vocabulary",
    description: "Days of the week and parts of the day.",
    cards: [
      { front: "Monday", front_de: "Monday", back: "Alatsinainy" },
      { front: "Tuesday", front_de: "Tuesday", back: "Talata" },
      { front: "Wednesday", front_de: "Wednesday", back: "Alarobia" },
      { front: "Thursday", front_de: "Thursday", back: "Alakamisy" },
      { front: "Friday", front_de: "Friday", back: "Zoma" },
      { front: "Saturday", front_de: "Saturday", back: "Sabotsy" },
      { front: "Sunday", front_de: "Sunday", back: "Alahady" },
      { front: "Yesterday", front_de: "Yesterday", back: "Omaly" },
      { front: "Today", front_de: "Today", back: "Androany" },
      { front: "Tomorrow", front_de: "Tomorrow", back: "Rahampitso" },
      { front: "Morning", front_de: "Morning", back: "Maraina" },
      { front: "Noon", front_de: "Noon", back: "Atoandro" },
      { front: "Afternoon", front_de: "Afternoon", back: "Tolakandro" },
      { front: "Evening", front_de: "Evening", back: "Hariva" },
      { front: "Night", front_de: "Night", back: "Alina" },
    ],
    vocab: [
      { malagasy: "Alatsinainy", english: "Monday", german: "Montag" },
      { malagasy: "Talata", english: "Tuesday", german: "Dienstag" },
      { malagasy: "Alarobia", english: "Wednesday", german: "Mittwoch" },
      { malagasy: "Alakamisy", english: "Thursday", german: "Donnerstag" },
      { malagasy: "Zoma", english: "Friday", german: "Freitag" },
      { malagasy: "Sabotsy", english: "Saturday", german: "Samstag" },
      { malagasy: "Alahady", english: "Sunday", german: "Sonntag" },
      { malagasy: "Omaly", english: "Yesterday", german: "Gestern" },
      { malagasy: "Androany", english: "Today", german: "Heute" },
      { malagasy: "Rahampitso", english: "Tomorrow", german: "Morgen" },
      { malagasy: "Maraina", english: "Morning", german: "Morgen" },
      { malagasy: "Atoandro", english: "Noon", german: "Mittag" },
      { malagasy: "Tolakandro", english: "Afternoon", german: "Nachmittag" },
      { malagasy: "Hariva", english: "Evening", german: "Abend" },
      { malagasy: "Alina", english: "Night", german: "Nacht" },
      { malagasy: "Andro", english: "Day", german: "Tag" },
      { malagasy: "Herinandro", english: "Week", german: "Woche" },
      { malagasy: "Volana", english: "Month", german: "Monat" },
      { malagasy: "Taona", english: "Year", german: "Jahr" },
      { malagasy: "Amin'ny", english: "At (time)", german: "Um (Zeit)" },
      { malagasy: "maraina be", english: "Early morning", german: "Frueher Morgen" },
      { malagasy: "tapitrisanandro", english: "Midnight", german: "Mitternacht" },
      { malagasy: "Afaka", english: "Later / After", german: "Spaeter / Nach" },
      { malagasy: "Taloha", english: "Before / Ago", german: "Vor / Vorher" },
      { malagasy: "Fotoana", english: "Time / Moment", german: "Zeit / Moment" },
      { malagasy: "Famindrana", english: "Appointment", german: "Termin" },
      { malagasy: "Fotoam-pihinanana", english: "Mealtime", german: "Essenszeit" },
      { malagasy: "Fotoam-piadiana", english: "Work time", german: "Arbeitszeit" },
      { malagasy: "Fialan-tsasatra", english: "Vacation / Holiday", german: "Urlaub / Ferien" },
      { malagasy: "Andro fety", english: "Holiday / Festival day", german: "Feiertag" },
      { malagasy: "Trondro", english: "Fish", german: "Fisch" },
    ],
    quiz: [
      { question: "What day is 'Alakamisy'?", question_de: "What day is 'Alakamisy'?", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], options_de: ["Tuesday", "Wednesday", "Thursday", "Friday"], correct: 2 },
      { question: "What does 'Androany' mean?", question_de: "What does 'Androany' mean?", options: ["Yesterday", "Today", "Tomorrow", "Now"], options_de: ["Yesterday", "Today", "Tomorrow", "Now"], correct: 1 },
      { question: "What does 'Hariva' mean?", question_de: "What does 'Hariva' mean?", options: ["Morning", "Noon", "Afternoon", "Evening"], options_de: ["Morning", "Noon", "Afternoon", "Evening"], correct: 3 },
    ]
  },
  {
    id: "feelings",
    title: "Feelings & Emotions",
    emoji: "😊",
    category: "vocabulary",
    description: "Expressing emotions and reactions.",
    cards: [
      { front: "That makes me happy.", front_de: "That makes me happy.", back: "Mahafaly ahy izany" },
      { front: "That's sad.", front_de: "That's sad.", back: "Mampalahelo izany" },
      { front: "That's surprising.", front_de: "That's surprising.", back: "Mahagaga izany" },
      { front: "That's shocking!", front_de: "That's shocking!", back: "Mahasosotra izany" },
      { front: "It's tiring.", front_de: "It's tiring.", back: "Mandreraka izany" },
      { front: "That's frightening!", front_de: "That's frightening!", back: "Mampatahotra izany" },
      { front: "That's annoying!", front_de: "That's annoying!", back: "Mahakamo izany" },
      { front: "That's doubtful.", front_de: "That's doubtful.", back: "Mampiahiahy izany" },
      { front: "Amusing! Hilarious!", front_de: "Amusing! Hilarious!", back: "Mampihomehy izany" },
      { front: "He/She is happy.", front_de: "He/She is happy.", back: "Faly izy." },
      { front: "I am sad.", front_de: "I am sad.", back: "Malahelo aho." },
      { front: "They are afraid.", front_de: "They are afraid.", back: "Matahotra izireo." },
    ],
    vocab: [
      { malagasy: "Faly", english: "happy", german: "gluecklich" },
      { malagasy: "Malahelo", english: "sad", german: "traurig" },
      { malagasy: "Gaga", english: "surprised", german: "ueberrascht" },
      { malagasy: "Sosotra", english: "shocked / angry", german: "geschockt / wuetend" },
      { malagasy: "Matahotra", english: "afraid", german: "aengstlich" },
      { malagasy: "Kamo", english: "lazy", german: "faul" },
      { malagasy: "Matoky", english: "to trust", german: "vertrauen" },
      { malagasy: "Halako", english: "I hate it", german: "Ich hasse es" },
      { malagasy: "Reraka", english: "tired", german: "muede" },
      { malagasy: "Mafana", english: "hot (person)", german: "heiss (Person)" },
      { malagasy: "Mangatsiaka", english: "cold (person)", german: "kalt (Person)" },
      { malagasy: "Tezitra", english: "angry", german: "wuetend" },
      { malagasy: "Manahy", english: "worried / anxious", german: "besorgt / aengstlich" },
      { malagasy: "Maniry", english: "to desire / want", german: "wollen" },
      { malagasy: "Matahotra", english: "scared", german: "aengstlich" },
      { malagasy: "Mahatsikaiky", english: "funny / amusing", german: "lustig / amuesant" },
      { malagasy: "Mampalahelo", english: "regrettable", german: "bedauerlich" },
      { malagasy: "Mahagaga", english: "amazing", german: "erstaunlich" },
      { malagasy: "Mahafaly", english: "pleasant", german: "angenehm" },
      { malagasy: "Mampiseho", english: "to show / express", german: "zeigen / ausdruecken" },
      { malagasy: "Manome", english: "to give", german: "geben" },
      { malagasy: "Mampianatra", english: "to teach", german: "lehren" },
      { malagasy: "Mianatra", english: "to learn", german: "lernen" },
      { malagasy: "Manome toky", english: "to reassure", german: "beruhigen" },
      { malagasy: "Mampahatsiahy", english: "to remind", german: "erinnern" },
      { malagasy: "Manadino", english: "to forget", german: "vergessen" },
      { malagasy: "Mahatsiaro", english: "to remember", german: "sich erinnern" },
      { malagasy: "Mankasitraka", english: "to appreciate", german: "schaetzen" },
      { malagasy: "Maneho hevitra", english: "to give an opinion", german: "eine Meinung aeussern" },
      { malagasy: "Manaiky", english: "to agree", german: "zustimmen" },
      { malagasy: "Manda", english: "to refuse", german: "ablehnen" },
      { malagasy: "Mahay", english: "to know how / can", german: "wissen wie / koennen" },
      { malagasy: "Tsy mahay", english: "to not know / cannot", german: "nicht wissen / koennen" },
      { malagasy: "Mahazo", english: "to receive / get", german: "erhalten / bekommen" },
      { malagasy: "Mandany", english: "to spend (time)", german: "verbringen (Zeit)" },
      { malagasy: "Mijery", english: "to watch / look at", german: "zuschauen / anschauen" },
    ],
    quiz: [
      { question: "What does 'Malahelo aho.' mean?", question_de: "What does 'Malahelo aho.' mean?", options: ["I am happy", "I am sad", "I am tired", "I am surprised"], options_de: ["I am happy", "I am sad", "I am tired", "I am surprised"], correct: 1 },
      { question: "What does 'Matahotra' mean?", question_de: "What does 'Matahotra' mean?", options: ["Angry", "Afraid", "Happy", "Tired"], options_de: ["Angry", "Afraid", "Happy", "Tired"], correct: 1 },
      { question: "What does 'Mahagaga izany' mean?", question_de: "What does 'Mahagaga izany' mean?", options: ["That's sad", "That's surprising", "That's funny", "That's enough"], options_de: ["That's sad", "That's surprising", "That's funny", "That's enough"], correct: 1 },
    ]
  },
  {
    id: "colors",
    title: "Colors",
    emoji: "🎨",
    category: "vocabulary",
    description: "Color vocabulary with shades.",
    cards: [
      { front: "Colors", front_de: "Colors", back: "Loko" },
      { front: "To be colored", front_de: "To be colored", back: "Miloko" },
      { front: "Blue", front_de: "Blue", back: "Manga" },
      { front: "Bluish", front_de: "Bluish", back: "Mangamanga" },
      { front: "Dark blue", front_de: "Dark blue", back: "Manga antitra" },
      { front: "Light blue", front_de: "Light blue", back: "Manga tanora" },
      { front: "Red", front_de: "Red", back: "Mena" },
      { front: "White", front_de: "White", back: "Fotsy" },
      { front: "Black", front_de: "Black", back: "Mainty" },
      { front: "Green", front_de: "Green", back: "Maintso" },
      { front: "Pink", front_de: "Pink", back: "Mavokely" },
      { front: "Yellow", front_de: "Yellow", back: "Mavo" },
      { front: "Orange", front_de: "Orange", back: "Volom-boasary" },
      { front: "Brown", front_de: "Brown", back: "Volon-tsokola" },
      { front: "Grey", front_de: "Grey", back: "Volon-davenona" },
    ],
    vocab: [
      { malagasy: "Manga", english: "Blue", german: "Blau" },
      { malagasy: "Mena", english: "Red", german: "Rot" },
      { malagasy: "Fotsy", english: "White", german: "Weiss" },
      { malagasy: "Mainty", english: "Black", german: "Schwarz" },
      { malagasy: "Maintso", english: "Green", german: "Gruen" },
      { malagasy: "Mavo", english: "Yellow", german: "Gelb" },
      { malagasy: "Mavokely", english: "Pink", german: "Rosa" },
      { malagasy: "Loko", english: "Colors", german: "Farben" },
      { malagasy: "Miloko", english: "To be colored", german: "Gefaerbt sein" },
      { malagasy: "Mangamanga", english: "Bluish", german: "Blaulich" },
      { malagasy: "Manga antitra", english: "Dark blue", german: "Dunkelblau" },
      { malagasy: "Manga tanora", english: "Light blue", german: "Hellblau" },
      { malagasy: "Volom-boasary", english: "Orange", german: "Orange" },
      { malagasy: "Volon-tsokola", english: "Brown", german: "Braun" },
      { malagasy: "Volon-davenona", english: "Grey", german: "Grau" },
      { malagasy: "Mena-mena", english: "Reddish", german: "Roetlich" },
      { malagasy: "Fotsy fotsy", english: "Very white", german: "Sehr weiss" },
      { malagasy: "Mainty mainty", english: "Very black / pitch black", german: "Sehr schwarz / pechschwarz" },
      { malagasy: "Mavo-mavo", english: "Yellowish", german: "Gelblich" },
      { malagasy: "Maintso mainty", english: "Dark green", german: "Dunkelgruen" },
      { malagasy: "Maintso tanora", english: "Light green", german: "Hellgruen" },
      { malagasy: "Loko anaty", english: "Color inside", german: "Farbe innen" },
      { malagasy: "Loko ivelany", english: "Color outside", german: "Farbe aussen" },
    ],
    quiz: [
      { question: "What does 'Maintso' mean?", question_de: "Was bedeutet 'Maintso'?", options: ["Blue", "Green", "Yellow", "Red"], options_de: ["Blau", "Gruen", "Gelb", "Rot"], correct: 1 },
      { question: "What does 'Fotsy' mean?", question_de: "Was bedeutet 'Fotsy'?", options: ["Black", "White", "Grey", "Red"], options_de: ["Schwarz", "Weiss", "Grau", "Rot"], correct: 1 },
    ]
  },
  {
    id: "furniture",
    title: "House & Furniture",
    emoji: "🏠",
    category: "vocabulary",
    description: "Items found in a typical home.",
    cards: [
      { front: "Chair", front_de: "Chair", back: "Seza" },
      { front: "Table", front_de: "Table", back: "Latabatra" },
      { front: "Bed frame", front_de: "Bed frame", back: "Farafara" },
      { front: "Mattress", front_de: "Mattress", back: "Kidoro" },
      { front: "Pillow", front_de: "Pillow", back: "Ondana" },
      { front: "Blankets", front_de: "Blankets", back: "Bodofotsy" },
      { front: "Towel", front_de: "Towel", back: "Servieta" },
      { front: "Light", front_de: "Light", back: "Jiro" },
      { front: "Door", front_de: "Door", back: "Varavarana" },
      { front: "Window", front_de: "Window", back: "Varavarankely" },
      { front: "Mosquito net", front_de: "Mosquito net", back: "Lay" },
      { front: "Plastic mug", front_de: "Plastic mug", back: "Zinga" },
      { front: "Bucket", front_de: "Bucket", back: "Sio" },
    ],
    vocab: [
      { malagasy: "Seza", english: "Chair", german: "Stuhl" },
      { malagasy: "Latabatra", english: "Table", german: "Tisch" },
      { malagasy: "Farafara", english: "Bed", german: "Bett" },
      { malagasy: "Kidoro", english: "Mattress", german: "Matratze" },
      { malagasy: "Lay", english: "Mosquito net", german: "Moskitonetz" },
      { malagasy: "Varavarankely", english: "Window", german: "Fenster" },
      { malagasy: "Varavarana", english: "Door", german: "Tuer" },
      { malagasy: "Ondana", english: "Pillow", german: "Kissen" },
      { malagasy: "Bodofotsy", english: "Blankets", german: "Decken" },
      { malagasy: "Servieta", english: "Towel", german: "Handtuch" },
      { malagasy: "Jiro", english: "Light", german: "Licht" },
      { malagasy: "Zinga", english: "Plastic mug", german: "Plastikbecher" },
      { malagasy: "Sio", english: "Bucket", german: "Eimer" },
      { malagasy: "Trano", english: "House", german: "Haus" },
      { malagasy: "Trano fandraisam-bahiny", english: "Guest house / Hotel", german: "Gaestehaus / Hotel" },
      { malagasy: "Trano fidiovana", english: "Bathroom", german: "Badezimmer" },
      { malagasy: "Trano fihinanana", english: "Dining room", german: "Esszimmer" },
      { malagasy: "Trano fandraisana", english: "Living room", german: "Wohnzimmer" },
      { malagasy: "Trano fambolena", english: "Farmhouse", german: "Bauernhaus" },
      { malagasy: "Tohatra", english: "Stairs", german: "Treppe" },
      { malagasy: "Rindrina", english: "Wall", german: "Wand" },
      { malagasy: "Tafotrano", english: "Roof", german: "Dach" },
      { malagasy: "Tany", english: "Floor / Ground", german: "Boden / Erde" },
      { malagasy: "Kodiarana", english: "Cement floor", german: "Zementboden" },
      { malagasy: "Kitapo", english: "Bag / Suitcase", german: "Tasche / Koffer" },
      { malagasy: "Sakafo", english: "Food", german: "Essen" },
      { malagasy: "Fanaka", english: "Furniture / Equipment", german: "Moebel / Ausruestung" },
      { malagasy: "Fitaovana", english: "Tools / Appliances", german: "Werkzeuge / Geraete" },
      { malagasy: "Jiro vony", english: "Flashlight", german: "Taschenlampe" },
      { malagasy: "Famantaranandro", english: "Clock / Watch", german: "Uhr" },
      { malagasy: "Radio", english: "Radio", german: "Radio" },
      { malagasy: "Serasera", english: "Fan", german: "Ventilator" },
      { malagasy: "Tapaka", english: "Cut / Broken", german: "Geschnitten / Kaputt" },
      { malagasy: "Madio", english: "Clean", german: "Sauber" },
      { malagasy: "Maloto", english: "Dirty", german: "Schmutzig" },
      { malagasy: "Mangatsiaka (trano)", english: "Cool (house)", german: "Kuehl (Haus)" },
      { malagasy: "Mafana (trano)", english: "Warm (house)", german: "Warm (Haus)" },
    ],
    quiz: [
      { question: "What does 'Lay' mean?", question_de: "Was bedeutet 'Lay'?", options: ["Pillow", "Blanket", "Mosquito net", "Bucket"], options_de: ["Pillow", "Blanket", "Mosquito net", "Bucket"], correct: 2 },
      { question: "What does 'Zinga' mean?", question_de: "Was bedeutet 'Zinga'?", options: ["Chair", "Table", "Plastic mug", "Door"], options_de: ["Chair", "Table", "Plastic mug", "Door"], correct: 2 },
    ]
  },
  {
    id: "verbs",
    title: "Verbs & Conjugation",
    emoji: "⚡",
    category: "grammar",
    description: "Master verb tenses and conjugation patterns in Malagasy.",
    content: {
      en: [
        { heading: "Tense Prefixes", body: "Malagasy verbs change tense through prefixes only. No person or number conjugation. Present: mi- / ma- / man- | Future: hi- / ha- / han- | Past: ni- / na- / nan-. Example root: -hianatra (to learn). mianatra = learn (present) | hianatra = will learn | nianatra = learned." },
        { heading: "Voice Variations", body: "Active: mi- (mividy = buy). Passive: voa- (voavidy = be bought). Causative: mamp- (mampianatra = teach). Reciprocal: mifank(a)- (mifankahalana = hate each other). The passive voice is common and often used where English uses active." },
        { heading: "Common Verbs", body: "mihinana = eat | misotro = drink | mianatra = learn | mandeha = go | mijery = look | mamely = hit | manome = give | mitady = search | manao = do/make | mividy = buy. Base form (infinitive) uses ha-/hi- prefix. Example: hianatra = to learn, hihinana = to eat." }
      ],
      de: [
        { heading: "Zeit-Praefixe", body: "Malagasy-Verben aendern die Zeit nur durch Praefixe. Keine Person- oder Zahlkonjugation. Gegenwart: mi- / ma- / man- | Zukunft: hi- / ha- / han- | Vergangenheit: ni- / na- / nan-. Beispiel Stamm: -hianatra (lernen). mianatra = lerne | hianatra = werde lernen | nianatra = lernte." },
        { heading: "Genus-Verbales (Stimmen)", body: "Aktiv: mi- (mividy = kaufen). Passiv: voa- (voavidy = gekauft werden). Kausativ: mamp- (mampianatra = lehren). Reziprok: mifank(a)- (mifankahalana = sich hassen). Die Passivstimme ist haeufig und wird oft dort verwendet, wo Deutsch Aktiv verwendet." },
        { heading: "Haeufige Verben", body: "mihinana = essen | misotro = trinken | mianatra = lernen | mandeha = gehen | mijery = anschauen | mamely = schlagen | manome = geben | mitady = suchen | manao = tun/machen | mividy = kaufen. Grundform (Infinitiv) verwendet ha-/hi-Praefix. Beispiel: hianatra = zu lernen, hihinana = zu essen." }
      ]
    },
    vocab: [
      { malagasy: "mihinana", english: "to eat (present)", german: "essen (Gegenwart)" },
      { malagasy: "hihinana", english: "will eat (future)", german: "werde essen (Zukunft)" },
      { malagasy: "nihinana", english: "ate (past)", german: "aß (Vergangenheit)" },
      { malagasy: "misotro", english: "to drink", german: "trinken" },
      { malagasy: "mandeha", english: "to go", german: "gehen" },
      { malagasy: "mitady", english: "to search", german: "suchen" },
      { malagasy: "manome", english: "to give", german: "geben" },
      { malagasy: "mampiasa", english: "to use", german: "benutzen" },
      { malagasy: "mijery", english: "to look at", german: "anschauen" },
      { malagasy: "miteny", english: "to speak", german: "sprechen" },
      { malagasy: "manao", english: "to do", german: "tun" },
      { malagasy: "mividy", english: "to buy", german: "kaufen" },
      { malagasy: "mamely", english: "to hit", german: "schlagen" },
      { malagasy: "mampihatra", english: "to enforce", german: "durchsetzen" },
      { malagasy: "voafetra", english: "to be limited", german: "begrenzt sein" },
      { malagasy: "mifankahalana", english: "to hate each other", german: "sich hassen" },
      { malagasy: "mankafy", english: "to enjoy", german: "geniessen" },
      { malagasy: "mipetraka", english: "to live", german: "leben" },
      { malagasy: "mianatra", english: "to learn", german: "lernen" },
      { malagasy: "mamorona", english: "to create", german: "erschaffen" },
      { malagasy: "mitady", english: "to search", german: "suchen" },
      { malagasy: "mividy", english: "to buy", german: "kaufen" },
      { malagasy: "manome", english: "to give", german: "geben" },
      { malagasy: "manao", english: "to do", german: "tun" },
      { malagasy: "mijery", english: "to look at", german: "anschauen" },
    ],
    quiz: [
      { question: "What prefix indicates future tense?", question_de: "What prefix indicates future tense?", options: ["mi-", "ni-", "hi-", "voa-"], options_de: ["mi-", "ni-", "hi-", "voa-"], correct: 2 },
      { question: "What prefix indicates past tense?", question_de: "What prefix indicates past tense?", options: ["mi-", "ni-", "hi-", "voa-"], options_de: ["mi-", "ni-", "hi-", "voa-"], correct: 1 },
      { question: "What does 'hihinana' mean?", question_de: "What does 'hihinana' mean?", options: ["eat (present)", "ate (past)", "will eat (future)", "eating"], options_de: ["eat (present)", "ate (past)", "will eat (future)", "eating"], correct: 2 },
      { question: "What is the passive voice prefix?", question_de: "What is the passive voice prefix?", options: ["mi-", "mamp-", "voa-", "ni-"], options_de: ["mi-", "mamp-", "voa-", "ni-"], correct: 2 },
      { question: "What does 'mifankahalana' mean?", question_de: "What does 'mifankahalana' mean?", options: ["to love each other", "to hate each other", "to meet each other", "to help each other"], options_de: ["to love each other", "to hate each other", "to meet each other", "to help each other"], correct: 1 },
    ]
  },
  {
    id: "pronouns",
    title: "Pronouns & Possession",
    emoji: "👤",
    category: "grammar",
    description: "Personal pronouns, demonstratives, and possession patterns.",
    content: {
      en: [
        { heading: "Personal Pronouns", body: "Aho = I | Ianao = You | Izy = He/She. Isika = We (incl. you) | Izahay = We (excl. you). Ianareo = You (pl.) | Izireo = They. There is no case distinction. 'Aho' means I, me, my, mine — context determines the role. Pronouns usually come at the end of the sentence as the subject." },
        { heading: "Demonstratives", body: "Ity = This (near me) | Iry = That (near you). Ireo = Those (plural) | Ila = That (far away). The singular/plural distinction is less strict than in English. 'Ireo' is commonly used for any plural 'those'." },
        { heading: "Possession", body: "Use 'ny' before the noun for general possession. Use suffixes for specific possession: -ko = my | -nako = your | -ny = his/her | -ntsika = our | -nareo = your (pl.) | -nazy = their. Example: Ny bokiko = My book. Example: Ny tranonao = Your house." }
      ],
      de: [
        { heading: "Persoenliche Pronomen", body: "Aho = Ich | Ianao = Du | Izy = Er/Sie. Isika = Wir (inkl. dich) | Izahay = Wir (exkl. dich). Ianareo = Ihr | Izireo = Sie. Es gibt keine Kasus-Unterscheidung. 'Aho' bedeutet ich/mir/meinem — Kontext bestimmt die Rolle. Pronomen stehen normalerweise am Satzende als Subjekt." },
        { heading: "Demonstrativpronomen", body: "Ity = Dieses (bei mir) | Iry = Jenes (bei dir). Ireo = Jene (Plural) | Ila = Jenes (weit weg). Die Singular/Plural-Unterscheidung ist weniger streng als im Deutschen. 'Ireo' wird allgemein fuer jeden Plural 'jene' verwendet." },
        { heading: "Besitz", body: "Verwende 'ny' vor dem Nomen fuer allgemeinen Besitz. Verwende Suffixe fuer spezifischen Besitz: -ko = mein | -nako = dein | -ny = sein/ihr | -ntsika = unser | -nareo = euer | -nazy = ihr. Beispiel: Ny bokiko = Mein Buch. Beispiel: Ny tranonao = Dein Haus." }
      ]
    },
    vocab: [
      { malagasy: "Aho", english: "I", german: "ich" },
      { malagasy: "Ianao", english: "You", german: "Du" },
      { malagasy: "Izy", english: "He/She", german: "Er/Sie" },
      { malagasy: "Isika", english: "We (inclusive)", german: "Wir (inklusiv)" },
      { malagasy: "Izahay", english: "We (exclusive)", german: "Wir (exklusiv)" },
      { malagasy: "Ianareo", english: "You (plural)", german: "Ihr" },
      { malagasy: "Izireo", english: "They", german: "Sie" },
      { malagasy: "Ity", english: "This", german: "Dies" },
      { malagasy: "Iry", english: "That", german: "Das" },
      { malagasy: "Ireo", english: "These/Those", german: "Diese/Jene" },
      { malagasy: "ny", english: "the / possession marker", german: "der/die/das / Besitzmarker" },
      { malagasy: "Ankoatra", english: "besides / except", german: "ausser" },
      { malagasy: "Samy", english: "each / every", german: "jede / jeder" },
      { malagasy: "Rehefa", english: "when (statement)", german: "wann (Aussage)" },
      { malagasy: "Raha", english: "if", german: "wenn" },
      { malagasy: "Satria", english: "because", german: "weil" },
      { malagasy: "Fa", english: "but", german: "aber" },
      { malagasy: "Dia", english: "then / and", german: "dann / und" },
      { malagasy: "Ary", english: "and", german: "und" },
      { malagasy: "Tsy misy", english: "there is not", german: "es gibt nicht" },
      { malagasy: "ve", english: "question particle", german: "Fragepartikel" },
      { malagasy: "angaha", english: "polite question particle", german: "hoefliche Fragepartikel" },
      { malagasy: "izany", english: "that / it", german: "das / es" },
      { malagasy: "koa", english: "too / also", german: "zu / auch" },
    ],
    quiz: [
      { question: "Which pronoun is inclusive (includes listener)?", question_de: "Which pronoun is inclusive (includes listener)?", options: ["Izahay", "Isika", "Ianareo", "Izireo"], options_de: ["Izahay", "Isika", "Ianareo", "Izireo"], correct: 1 },
      { question: "Which demonstrative means 'far from speaker'?", question_de: "Which demonstrative means 'far from speaker'?", options: ["Ity", "Iry", "Ireo", "Izy"], options_de: ["Ity", "Iry", "Ireo", "Izy"], correct: 1 },
      { question: "What does 'Raha' mean?", question_de: "What does 'Raha' mean?", options: ["because", "if", "but", "then"], options_de: ["because", "if", "but", "then"], correct: 1 },
      { question: "What does 'Rehefa' mean?", question_de: "What does 'Rehefa' mean?", options: ["when (question)", "when (statement)", "why", "how"], options_de: ["when (question)", "when (statement)", "why", "how"], correct: 1 },
      { question: "Which conjunction means 'because'?", question_de: "Which conjunction means 'because'?", options: ["Fa", "Dia", "Satria", "Ary"], options_de: ["Fa", "Dia", "Satria", "Ary"], correct: 2 },
    ]
  },
  {
    id: "adjectives",
    title: "Adjectives & Descriptions",
    emoji: "✨",
    category: "grammar",
    description: "How adjectives work in Malagasy — placement, intensifiers, and comparison.",
    content: {
      en: [
        { heading: "Adjective Placement", body: "Adjectives ALWAYS come after the noun. Example: Trano lehibe = big house (house big). Example: Zazakely tsara = good little child. There is no 'to be' verb. The adjective acts as the predicate directly. 'Manga izy' = Blue he/she = 'It is blue'." },
        { heading: "Intensifiers", body: "More / -er: kokoa. Example: Lehibe kokoa = bigger. Most / -est: indrindra. Example: Tsara indrindra = best. Very: be- prefix. Example: Bevoka = very wet. Diminutive: -kely suffix. Example: Zazakely = small child. Augmentative: -be suffix. Example: Tanabe = big town." },
        { heading: "Common Adjectives", body: "Tsara = good | Ratsy = bad. Lehibe = big | Kely = small. Lava = long | Fohy = short. Mora = easy/cheap | Sarotra = difficult/expensive. Madio = clean | Maloto = dirty. Vaovao = new | Taloha = old. Negation: Tsy + adjective. Example: Tsy tsara = not good." }
      ],
      de: [
        { heading: "Adjektivstellung", body: "Adjektive stehen IMMER nach dem Nomen. Beispiel: Trano lehibe = grosses Haus (Haus gross). Beispiel: Zazakely tsara = gutes kleines Kind. Es gibt kein 'sein'-Verb. Das Adjektiv fungiert direkt als Praedikat. 'Manga izy' = Blau er/sie = 'Es ist blau'." },
        { heading: "Intensivierung", body: "Mehr / -er: kokoa. Beispiel: Lehibe kokoa = groesser. Am meisten / -ste: indrindra. Beispiel: Tsara indrindra = am besten. Sehr: be-Praefix. Beispiel: Bevoka = sehr nass. Verkleinerung: -kely Suffix. Beispiel: Zazakely = kleines Kind. Vergrösserung: -be Suffix. Beispiel: Tanabe = grosse Stadt." },
        { heading: "Haeufige Adjektive", body: "Tsara = gut | Ratsy = schlecht. Lehibe = gross | Kely = klein. Lava = lang | Fohy = kurz. Mora = einfach/billig | Sarotra = schwierig/teuer. Madio = sauber | Maloto = schmutzig. Vaovao = neu | Taloha = alt. Verneinung: Tsy + Adjektiv. Beispiel: Tsy tsara = nicht gut." }
      ]
    },
    vocab: [
      { malagasy: "lehibe", english: "big", german: "gross" },
      { malagasy: "kely", english: "small", german: "klein" },
      { malagasy: "lava", english: "long", german: "lang" },
      { malagasy: "fohy", english: "short", german: "kurz" },
      { malagasy: "tsara", english: "good", german: "gut" },
      { malagasy: "ratsy", english: "bad", german: "schlecht" },
      { malagasy: "vaovao", english: "new", german: "neu" },
      { malagasy: "taloha", english: "old", german: "alt" },
      { malagasy: "mora", english: "easy / cheap", german: "einfach / billig" },
      { malagasy: "sarotra", english: "difficult / expensive", german: "schwierig / teuer" },
      { malagasy: "madio", english: "clean", german: "sauber" },
      { malagasy: "maloto", english: "dirty", german: "schmutzig" },
      { malagasy: "maro", english: "many", german: "viele" },
      { malagasy: "vitsy", english: "few", german: "wenige" },
      { malagasy: "rehetra", english: "all", german: "alle" },
      { malagasy: "sasany", english: "some", german: "einige" },
      { malagasy: "hafa", english: "different", german: "anders" },
      { malagasy: "mitovy", english: "same", german: "gleich" },
      { malagasy: "kokoa", english: "more", german: "mehr" },
      { malagasy: "indrindra", english: "most / especially", german: "am meisten / besonders" },
      { malagasy: "be-", english: "very (prefix)", german: "sehr (Praefix)" },
      { malagasy: "-kely", english: "small (suffix)", german: "klein (Suffix)" },
      { malagasy: "-be", english: "big (suffix)", german: "gross (Suffix)" },
      { malagasy: "antitra", english: "dark (with colors)", german: "dunkel (mit Farben)" },
      { malagasy: "tanora", english: "light (with colors)", german: "hell (mit Farben)" },
    ],
    quiz: [
      { question: "Where do adjectives go in Malagasy?", question_de: "Where do adjectives go in Malagasy?", options: ["Before the noun", "After the noun", "At the start of sentence", "Anywhere"], options_de: ["Before the noun", "After the noun", "At the start of sentence", "Anywhere"], correct: 1 },
      { question: "What does 'kokoa' mean?", question_de: "What does 'kokoa' mean?", options: ["most", "more", "very", "less"], options_de: ["most", "more", "very", "less"], correct: 1 },
      { question: "What does 'indrindra' mean?", question_de: "What does 'indrindra' mean?", options: ["more", "most", "very", "little"], options_de: ["more", "most", "very", "little"], correct: 1 },
      { question: "What suffix makes something small?", question_de: "What suffix makes something small?", options: ["-be", "-kely", "-tsara", "-lava"], options_de: ["-be", "-kely", "-tsara", "-lava"], correct: 1 },
      { question: "What does 'Tsy tsara' mean?", question_de: "What does 'Tsy tsara' mean?", options: ["Very good", "Not good", "Good too", "Best"], options_de: ["Very good", "Not good", "Good too", "Best"], correct: 1 },
    ]
  },
  {
    id: "prepositions",
    title: "Prepositions & Location",
    emoji: "📍",
    category: "grammar",
    description: "Spatial and temporal prepositions for describing where and when things happen.",
    content: {
      en: [
        { heading: "Location Words", body: "Aty = here (near me). Any = there (near you / mid-distance). Ao = inside | Ivelany = outside. Example: Avia aty! = Come here! Example: Ao an-trano = Inside the house. Example: Ivelany ny trano = Outside the house." },
        { heading: "Direction & Position", body: "Talohan'ny = before | Aorian'ny = after. Manodidina = around | Miaraka amin'ny = with. Any an-tampony = on top | Any ambany = underneath. Any akaiky = nearby | Any lavitra = far away. Example: Talohan'ny latabatra = Before the table. Example: Manodidina ny trano = Around the house." },
        { heading: "General Preposition", body: "Amin'ny = at / in / on / by (general). It is the all-purpose preposition whose exact meaning depends on context. Example: Amin'ny alina = at night. Example: Amin'ny tany = on the ground. Example: Amin'ny sisin'ny = at the edge of." }
      ],
      de: [
        { heading: "Ortsangaben", body: "Aty = hier (bei mir). Any = dort (bei dir / mittlere Entfernung). Ao = drinnen | Ivelany = draussen. Beispiel: Avia aty! = Komm her! Beispiel: Ao an-trano = Drinnen im Haus. Beispiel: Ivelany ny trano = Draussen vom Haus." },
        { heading: "Richtung & Position", body: "Talohan'ny = vor | Aorian'ny = nach. Manodidina = herum | Miaraka amin'ny = mit. Any an-tampony = oben drauf | Any ambany = darunter. Any akaiky = in der Naehe | Any lavitra = weit weg. Beispiel: Talohan'ny latabatra = Vor dem Tisch. Beispiel: Manodidina ny trano = Um das Haus herum." },
        { heading: "Allgemeine Praeposition", body: "Amin'ny = bei / in / auf / an (allgemein). Es ist die Universall-Praeposition, deren genaue Bedeutung vom Kontext abhaengt. Beispiel: Amin'ny alina = bei Nacht. Beispiel: Amin'ny tany = auf dem Boden. Beispiel: Amin'ny sisin'ny = am Rand von." }
      ]
    },
    vocab: [
      { malagasy: "Amin'ny", english: "at / in / on", german: "bei / in / auf" },
      { malagasy: "Any", english: "there", german: "dort" },
      { malagasy: "Aty", english: "here", german: "hier" },
      { malagasy: "Ao", english: "inside", german: "drinnen" },
      { malagasy: "Ivelany", english: "outside", german: "draussen" },
      { malagasy: "Tampony", english: "top", german: "Oben" },
      { malagasy: "Ambany", english: "underneath", german: "darunter" },
      { malagasy: "Akaiky", english: "nearby", german: "in der Naehe" },
      { malagasy: "Lavitra", english: "far", german: "weit" },
      { malagasy: "Soroka", english: "corner", german: "Ecke" },
      { malagasy: "Sisin'ny", english: "edge", german: "Rand" },
      { malagasy: "Afovoany", english: "middle", german: "Mitte" },
      { malagasy: "Farany", english: "end", german: "Ende" },
      { malagasy: "Talohan'ny", english: "before", german: "vor" },
      { malagasy: "Aorian'ny", english: "after", german: "nach" },
      { malagasy: "Miaraka amin'ny", english: "with", german: "mit" },
      { malagasy: "Manodidina", english: "around", german: "herum" },
      { malagasy: "Amin'ny ala", english: "in the forest", german: "im Wald" },
      { malagasy: "Amin'ny tany", english: "on the ground", german: "auf dem Boden" },
      { malagasy: "Amin'ny an-tampony", english: "on top", german: "oben drauf" },
      { malagasy: "Amin'ny ambany", english: "underneath", german: "darunter" },
      { malagasy: "Tsy misy afa-tsy", english: "except", german: "ausser" },
      { malagasy: "Ao an-trano", english: "inside the house", german: "im Haus" },
      { malagasy: "Ivelan'ny", english: "outside of", german: "ausserhalb" },
      { malagasy: "Any an-tampony", english: "on top of it", german: "darauf" },
    ],
    quiz: [
      { question: "What does 'Aty' mean?", question_de: "What does 'Aty' mean?", options: ["There", "Here", "Inside", "Outside"], options_de: ["There", "Here", "Inside", "Outside"], correct: 1 },
      { question: "What does 'Ao' mean?", question_de: "What does 'Ao' mean?", options: ["Outside", "Inside", "Here", "There"], options_de: ["Outside", "Inside", "Here", "There"], correct: 1 },
      { question: "What does 'Talohan'ny' mean?", question_de: "What does 'Talohan'ny' mean?", options: ["After", "Before", "During", "Between"], options_de: ["After", "Before", "During", "Between"], correct: 1 },
      { question: "What does 'Miaraka amin'ny' mean?", question_de: "What does 'Miaraka amin'ny' mean?", options: ["Without", "With", "Before", "After"], options_de: ["Without", "With", "Before", "After"], correct: 1 },
      { question: "What does 'Manodidina' mean?", question_de: "What does 'Manodidina' mean?", options: ["Through", "Around", "Over", "Under"], options_de: ["Through", "Around", "Over", "Under"], correct: 1 },
    ]
  },
  {
    id: "negation",
    title: "Negation & Modifiers",
    emoji: "🚫",
    category: "grammar",
    description: "How to negate sentences, form questions, and use modifiers.",
    content: {
      en: [
        { heading: "Negation Words", body: "tsy = not / no. Example: Tsy tsara = Not good. aza = don't (imperative). Example: Aza manao izany! = Don't do that! Tsy misy = there is not. Example: Tsy misy vary = There is no rice. Tsy afaka = cannot. Example: Tsy afaka mianatra aho = I cannot study. Tsy maintsy = must. Example: Tsy maintsy mandeha aho = I must go. Tsy azo atao = impossible. Example: Tsy azo atao izany = That's impossible." },
        { heading: "Temporal Modifiers", body: "efa = already. Example: Efa tonga izy = He has already arrived. mbola = still / yet. Example: Mbola tsara izy = It is still good. vao = just / recently. Example: Vao niverena izy = He just returned. indray = again. Example: Indray avy eo = Once more. tamin'ny = at the time of. Example: Tamin'ny maraina = In the morning." },
        { heading: "Question Particles", body: "ve = yes/no question marker. Example: Misy vary ve? = Is there rice? angaha = polite question. Example: Tsara angaha? = Is it good? (polite). Other useful modifiers: fotsiny = just / simply. tena = really / truly. koa = also / too. ihany = only / just." }
      ],
      de: [
        { heading: "Verneinungswoerter", body: "tsy = nicht / nein. Beispiel: Tsy tsara = Nicht gut. aza = nicht tun (Imperativ). Beispiel: Aza manao izany! = Mach das nicht! Tsy misy = es gibt nicht. Beispiel: Tsy misy vary = Es gibt keinen Reis. Tsy afaka = kann nicht. Beispiel: Tsy afaka mianatra aho = Ich kann nicht lernen. Tsy maintsy = muss. Beispiel: Tsy maintsy mandeha aho = Ich muss gehen. Tsy azo atao = unmoeglich. Beispiel: Tsy azo atao izany = Das ist unmoeglich." },
        { heading: "Zeitliche Modifikatoren", body: "efa = bereits. Beispiel: Efa tonga izy = Er ist bereits angekommen. mbola = immer noch / noch. Beispiel: Mbola tsara izy = Es ist immer noch gut. vao = gerade / kuerzlich. Beispiel: Vao niverena izy = Er ist gerade zurueckgekommen. indray = wieder. Beispiel: Indray avy eo = Noch einmal. tamin'ny = zur Zeit von. Beispiel: Tamin'ny maraina = Am Morgen." },
        { heading: "Fragepartikel", body: "ve = Ja/Nein-Fragemarke. Beispiel: Misy vary ve? = Gibt es Reis? angaha = hoefliche Frage. Beispiel: Tsara angaha? = Ist es gut? (hoeflich). Weitere nuetzliche Modifikatoren: fotsiny = einfach / nur. tena = wirklich / tatsaechlich. koa = auch / ebenfalls. ihany = nur / bloss." }
      ]
    },
    vocab: [
      { malagasy: "Tsy", english: "no / not", german: "nein / nicht" },
      { malagasy: "Tsy misy", english: "there is not", german: "es gibt nicht" },
      { malagasy: "Tsy maintsy", english: "must", german: "muessen" },
      { malagasy: "Tsy afaka", english: "cannot", german: "kann nicht" },
      { malagasy: "Tsy tia", english: "do not like", german: "nicht moegen" },
      { malagasy: "Aza", english: "don't", german: "nicht" },
      { malagasy: "Tsy azo atao", english: "impossible", german: "unmoeglich" },
      { malagasy: "Ve", english: "question particle", german: "Fragepartikel" },
      { malagasy: "Angaha", english: "polite question", german: "hoefliche Frage" },
      { malagasy: "Mbola", english: "still", german: "immer noch" },
      { malagasy: "Efa", english: "already", german: "bereits" },
      { malagasy: "Vao", english: "just / recently", german: "gerade / kuerzlich" },
      { malagasy: "tsara", english: "good", german: "gut" },
      { malagasy: "tsy tsara", english: "not good", german: "nicht gut" },
      { malagasy: "misy", english: "there is", german: "es gibt" },
      { malagasy: "tsy misy", english: "there is not", german: "es gibt nicht" },
      { malagasy: "maintsy", english: "must", german: "muessen" },
      { malagasy: "afaka", english: "can", german: "koennen" },
      { malagasy: "tsy afaka", english: "cannot", german: "kann nicht" },
      { malagasy: "tia", english: "to like", german: "moegen" },
      { malagasy: "tsy tia", english: "to not like", german: "nicht moegen" },
      { malagasy: "azo atao", english: "possible", german: "moeglich" },
      { malagasy: "tsy azo atao", english: "impossible", german: "unmoeglich" },
      { malagasy: "maintsy mandeha", english: "must go", german: "muss gehen" },
      { malagasy: "efa tonga", english: "already arrived", german: "bereits angekommen" },
    ],
    quiz: [
      { question: "What does 'Tsy' mean?", question_de: "Was bedeutet 'Tsy'?", options: ["yes", "no / not", "maybe", "please"], options_de: ["yes", "no / not", "maybe", "please"], correct: 1 },
      { question: "What does 'Aza' mean?", question_de: "Was bedeutet 'Aza'?", options: ["do", "don't", "can", "must"], options_de: ["do", "don't", "can", "must"], correct: 1 },
      { question: "What does 'Mbola' mean?", question_de: "Was bedeutet 'Mbola'?", options: ["already", "still", "never", "soon"], options_de: ["already", "still", "never", "soon"], correct: 1 },
      { question: "What does 'Efa' mean?", question_de: "Was bedeutet 'Efa'?", options: ["just", "already", "never", "soon"], options_de: ["just", "already", "never", "soon"], correct: 1 },
      { question: "What does 'Vao' mean?", question_de: "Was bedeutet 'Vao'?", options: ["old", "just / recently", "always", "never"], options_de: ["old", "just / recently", "always", "never"], correct: 1 },
    ]
  }
];

// ============================================
// EXTENDING LESSONS — HOW TO
// ============================================
// Just append a new object to the LESSONS array above:
//
// {
//   id: "unique-id",
//   title: "Lesson Title",
//   emoji: "🔥",
//   category: "conversation|vocabulary|grammar|basics",
//   description: "Short description.",
//   cards: [
//     { front: "Malagasy phrase", front_de: "Malagasy phrase", back: "English meaning" },
//     ...
//   ],
//   vocab: [
//     { malagasy: "word", english: "translation", german: "Uebersetzung" },
//     ...
//   ],
//   quiz: [
//     { question: "Question?", question_de: "Question?", options: ["A","B","C","D"], options_de: ["A","B","C","D"], correct: 0 },
//     ...
//   ]
// }
//
// The app auto-discovers new lessons on reload.
// ============================================

// Flatten all vocabulary for search
const ALL_VOCAB = (() => {
  const vocab = [];
  LESSONS.forEach(lesson => {
    if (lesson.vocab) {
      lesson.vocab.forEach(v => {
        vocab.push({
          malagasy: v.malagasy,
          english: v.english,
          german: v.german || '',
          lessonId: lesson.id,
          lessonTitle: lesson.title
        });
      });
    }
  });
  // deduplicate by malagasy word
  const seen = new Set();
  return vocab.filter(v => {
    if (seen.has(v.malagasy.toLowerCase())) return false;
    seen.add(v.malagasy.toLowerCase());
    return true;
  });
})();
